export {default as Header} from './Header/Header'
export {default as Hero } from './Hero/Hero'
export {default as Footer} from './Footer/Footer'
export {default as Heroa} from './Heroa/Heroa'
export {default as Heroc} from './Heroc/Heroc'